[package]
name = "carltonj2000_art"
version = "0.1.0"
authors = ["carltonj2000"]
description = "A library"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
